### ISSUE TITLE
希望增加logto和aigc-gateway使用非根路径的配置方式

### ISSUE THREAD

**Issue by keisni** [CloudNativeGame/aigc-gateway#24]
在values.yaml中增加选项，作用是生成的logto和aigc-gateway相关ingress资源使用非"/"的Path。目的是减少域名申请的数量，加快部署体验。

**Comment by chrisliu1995** [comment]
“减少域名申请的数量”，这里特指哪种域名申请的数量，可以再具体描述一下吗

**Comment by chrisliu1995** [comment]
“减少域名申请的数量”，这里特指哪种域名申请的数量，可以再具体描述一下吗

**Comment by keisni** [comment]
实际部署之后，这个特性也不是必要的，可以关闭。
