### ISSUE TITLE
增强web前端界面的交互效果

### ISSUE THREAD

**Issue by keisni** [CloudNativeGame/aigc-gateway#30]
现在web前端界面，当点击INSTALL、PAUSE、RESUME按钮之后，界面没有任何变化，只能通过刷新来改变界面状态，交互体验较差，且很容易让用户误以为操作没有成功从而重复操作。
期望在按钮点击之后，界面能即使自动相应更新，比如出现操作中的状态提示，同时避免用户重复点击。

**Comment by chrisliu1995** [comment]
https://github.com/CloudNativeGame/aigc-gateway/pull/12 and https://github.com/CloudNativeGame/aigc-gateway/pull/31 can solve your problem
